# Generated by Django 5.0 on 2024-01-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='horario',
            field=models.TimeField(default=16),
        ),
    ]
