# Generated by Django 5.0 on 2024-01-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0002_match_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='horario',
            field=models.TimeField(default='16:00'),
        ),
    ]
